# Generated by Django 4.2.6 on 2024-03-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvApp', '0004_custuser_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custuser',
            name='new',
        ),
    ]
