# Generated by Django 4.2.6 on 2024-03-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvApp', '0007_alter_complaint_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
