# Generated by Django 4.2.6 on 2024-03-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvApp', '0008_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
