# Generated by Django 4.2.6 on 2024-03-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvApp', '0009_complaint_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='name',
            new_name='username',
        ),
    ]
