# Generated by Django 4.2.6 on 2024-03-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvApp', '0010_rename_name_complaint_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='feedback',
            field=models.TextField(null=True),
        ),
    ]
