# Generated by Django 4.2.6 on 2024-03-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvApp', '0012_complaint_detail_head_complaint_detail_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
